eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_LEASE_RENEWAL_INTERVAL_SECONDS:5}
eureka.client.registry-fetch-interval-seconds=${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
eureka.instance.preferIpAddress=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.instanceId=${spring.application.name}:${spring.application.instance_id:${random.value}}

management.endpoints.web.exposure.include=health,info,refresh
management.endpoint.health.show-details=always
