spring.cloud.gateway.server.webmvc.routes[0].id=resourceModule
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://resource-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/resources/**
spring.cloud.gateway.server.webmvc.routes[1].id=songModule
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://song-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/songs/**
spring.cloud.gateway.server.webmvc.routes[2].id=storageModule
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://storage-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/storages/**

spring.web.resources.add-mappings=false
spring.web.error.whitelabel.enabled=false
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
