resource-service.api.url=${RESOURCE_SERVICE_URL:http://localhost:8071/resources}
song-service.api.url=${SONG_SERVICE_URL:http://localhost:8072/songs}

rabbitmq.queue=resource.queue

retry.max-retries=3
retry.delay-millis=3000
retry.multiplier=2
retry.max-delay-millis=5000
retry.jitter-millis=50
retry.timeout-seconds=30
