resource-service.api.url=${RESOURCE_SERVICE_URL:http://localhost:8071/resources}
song-service.api.url=${SONG_SERVICE_URL:http://localhost:8072/songs}

rabbitmq.exchange=resource.exchange
rabbitmq.queue=resource.queue
rabbitmq.processed-queue=resource.processed.queue
rabbitmq.processed-routing-key=resource.processed

retry.max-retries=3
retry.delay-millis=3000
retry.multiplier=2
retry.max-delay-millis=5000
retry.jitter-millis=50
retry.timeout-seconds=30
