song-service.api.url=${SONG_SERVICE_URL:http://localhost:8072/songs}

rabbitmq.exchange=resource.exchange
rabbitmq.queue=resource.queue
rabbitmq.routing-key=resource.uploaded

retry.max-retries=3
retry.delay-millis=3000
retry.multiplier=2
retry.max-delay-millis=5000
retry.jitter-millis=50
retry.timeout-seconds=30

management.endpoints.web.exposure.include=health,info,refresh,prometheus,circuitbreakers