song-service.api.url=${SONG_SERVICE_URL:http://localhost:8072/songs}
storage-service.api.url=${STORAGE_SERVICE_URL:http://localhost:8074/storages}

rabbitmq.exchange=resource.exchange
rabbitmq.queue=resource.queue
rabbitmq.routing-key=resource.uploaded
rabbitmq.processed-queue=resource.processed.queue
rabbitmq.processed-routing-key=resource.processed

retry.max-retries=3
retry.delay-millis=3000
retry.multiplier=2
retry.max-delay-millis=5000
retry.jitter-millis=50
retry.timeout-seconds=30

management.endpoints.web.exposure.include=health,info,refresh,circuitbreakers
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.storageService.register-health-indicator=true
resilience4j.circuitbreaker.instances.storageService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.storageService.sliding-window-size=10
resilience4j.circuitbreaker.instances.storageService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.storageService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.storageService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.storageService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.storageService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.storageService.ignore-exceptions=org.epam.learn.resource_service.exception.ResourceNotFoundException

