spring.datasource.url=${STORAGE_DB_URL:jdbc:postgresql://localhost:5434/storage_db}
spring.datasource.username=${STORAGE_DB_USER:postgres}
spring.datasource.password=${STORAGE_DB_PASSWORD:postgres}
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_LEASE_RENEWAL_INTERVAL_SECONDS:5}
aws.s3.endpoint=${AWS_S3_ENDPOINT:http://localhost:4566}
aws.s3.region=${AWS_DEFAULT_REGION:us-east-1}
aws.s3.access-key=${AWS_ACCESS_KEY_ID:test}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY:test}
storage.seed.staging-bucket=${STORAGE_STAGING_BUCKET:staging-bucket}
storage.seed.permanent-bucket=${STORAGE_PERMANENT_BUCKET:permanent-bucket}

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.cloud.config.fail-fast=false